In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
np.array(mylist)

array([1, 2, 3])

In [5]:
 nested_list = [[1,2],[3,4],[5,6]]

In [6]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [17]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    
    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
    
    See Also
    -

In [20]:
np.random.rand(2)

array([0.660241  , 0.65337496])

In [21]:
np.random.rand(3,4)

array([[0.79667764, 0.93780514, 0.39076832, 0.3530569 ],
       [0.00754685, 0.8958867 , 0.87963071, 0.61881637],
       [0.04569752, 0.646459  , 0.34399121, 0.0442399 ]])

In [22]:
np.random.rand(5,5)

array([[0.86908081, 0.31795448, 0.9426123 , 0.31475831, 0.87221773],
       [0.41736211, 0.28389988, 0.47316629, 0.72335019, 0.50185088],
       [0.46685457, 0.56245904, 0.98602704, 0.95234317, 0.77132848],
       [0.97426411, 0.28574437, 0.74488325, 0.59924454, 0.45267627],
       [0.1664051 , 0.12152169, 0.99898175, 0.35241795, 0.52625406]])

In [24]:
np.random.randint(1,100)

4

In [25]:
np.random.randint(1,100,5)

array([46,  5, 97, 44, 72])

In [26]:
np.random.randint(1,100,(2,3))

array([[49, 51, 52],
       [58, 45, 77]])

In [29]:
np.random.seed(42)
np.random.randint(1,100,(2,3))

array([[52, 93, 15],
       [72, 61, 21]])

In [30]:
arr = np.arange(25)

In [31]:
ranarr = np.random.randint(0,50,10)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [34]:
arr.shape

(25,)

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
arr.reshape(3,6)

ValueError: cannot reshape array of size 25 into shape (3,6)

In [41]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [37]:
ranarr.max()

39

In [38]:
ranarr.min()

2

In [39]:
# index of minimum value
ranarr.argmin()

9

In [40]:
# index of maxiumu value
ranarr.argmax()

7

In [42]:
ranarr.dtype

dtype('int64')

In [43]:
myarr = np.random.rand(4)

In [44]:
myarr

array([0.02058449, 0.96990985, 0.83244264, 0.21233911])

In [45]:
myarr.dtype

dtype('float64')